import DashboardLayout from "@/components/layout/dashboard";
import ToggleModeButton from "@/components/toggle-mode-button";
import { Toaster } from "sonner";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <DashboardLayout>{children}</DashboardLayout>
      <Toaster />
    </>
  );
}
